# Generated by Django 5.2.5 on 2025-08-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_core', '0002_ticket_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tur',
            field=models.CharField(choices=[('1', 'Teknik Problem'), ('2', 'Kullanıcı Bildirimi'), ('3', 'Ekip')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
