# Generated by Django 5.2.6 on 2025-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_core', '0003_ticket_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='destek/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tur',
            field=models.CharField(choices=[('1', 'Teknik Problem'), ('2', 'Kullanıcı Bildirimi'), ('3', 'Ekip'), ('4', 'Onaylı Kullanıcı')], max_length=1),
        ),
    ]
