# Generated by Django 5.2.6 on 2025-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_core', '0004_ticket_resim_alter_ticket_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tur',
            field=models.CharField(choices=[('0', 'Kimlik Doğrulaması'), ('1', 'Teknik Problem'), ('2', 'Kullanıcı Bildirimi'), ('3', 'Ekip'), ('4', 'Onaylı Kullanıcı')], max_length=1),
        ),
    ]
