# Generated by Django 5.2.6 on 2025-11-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_core', '0006_ticket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='yetkili_mesaj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
