# Generated by Django 5.2.5 on 2025-08-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_blog', '0002_gonderi_kapak_resmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonderi',
            name='kapak_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='post_resimleri/'),
        ),
    ]
