# Generated by Django 5.2.5 on 2025-09-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_mesaj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sohbet',
            name='katilimcilar',
        ),
        migrations.DeleteModel(
            name='Mesaj',
        ),
        migrations.DeleteModel(
            name='Sohbet',
        ),
    ]
