# Generated by Django 5.2.6 on 2025-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_mesaj', '0004_mesaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='okunma',
            field=models.BooleanField(default=False),
        ),
    ]
