# Generated by Django 5.2.5 on 2025-09-05 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0007_customuser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliciTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('metin', models.TextField()),
                ('süre', models.CharField(choices=[('1', 'Gün içerisinde'), ('2', 'Birkaç gün içinde'), ('3', 'Bir hafta içinde'), ('4', 'Bir ay içinde'), ('5', 'Süre henüz belirtilmedi')], max_length=1)),
                ('butce', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yazar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alıcı Talebi',
                'verbose_name_plural': 'Alıcı Talepleri',
                'db_table': 'alicitalebi',
            },
        ),
    ]
