# Generated by Django 5.2.5 on 2025-09-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0008_alicitalebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='etiketler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
