# Generated by Django 5.2.5 on 2025-09-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0011_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='kategori',
            field=models.CharField(blank=True, choices=[('teknoloji', 'Teknoloji'), ('sanat', 'Sanat'), ('tamir', 'Tamir'), ('eglence', 'Eğlence'), ('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('moda', 'Moda'), ('diger', 'Diğer')], default='diger', max_length=20, null=True),
        ),
    ]
