# Generated by Django 5.2.5 on 2025-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0012_ilan_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onayli_kullanici',
            field=models.BooleanField(default=False),
        ),
    ]
