# Generated by Django 5.2.5 on 2025-09-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0013_customuser_onayli_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iletisim_bilgilerimi_goster',
            field=models.BooleanField(default=False),
        ),
    ]
