from .index import index
from .ticket import ticket_olustur
from .sss import sss
from .gizlilik import gizlilik
from .manifest import manifest
from .assetlinks import assetlinks
from .kullanim_kosullari import kullanim_kosullari
from .indir import indir
from .my_tickets import my_tickets
from .ticket_detail import ticket_detail
from .go_profile import go_profile