# Generated by Django 5.2.6 on 2025-12-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('konu', models.TextField()),
                ('sure', models.CharField(choices=[('1', 'Gün içerisinde'), ('2', 'Birkaç gün içinde'), ('3', 'Bir hafta içinde'), ('4', 'Bir ay içinde'), ('5', 'Süre henüz belirtilmedi')], max_length=1)),
                ('ucret', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olusturan', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'db_table': 'projeler',
            },
        ),
    ]
