# Generated by Django 5.2.5 on 2025-08-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderi',
            name='kapak_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_resimleri/'),
        ),
    ]
