# Generated by Django 5.2.5 on 2025-09-01 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_baslik', models.CharField(max_length=150)),
                ('ilan_metni', models.TextField(max_length=1000)),
                ('konum', models.CharField(blank=True, max_length=25, null=True)),
                ('is_deneyimi', models.TextField()),
                ('ilan_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'db_table': 'ilan',
            },
        ),
    ]
