# Generated by Django 5.2.5 on 2025-09-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0005_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ilan',
            name='istenilen_ucret',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
