# Generated by Django 5.2.5 on 2025-09-05 19:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0006_ilan_aktif_ilan_istenilen_ucret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='get_full_name', unique=True),
        ),
    ]
