# Generated by Django 5.2.5 on 2025-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0009_ilan_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_name_visible',
            field=models.BooleanField(default=False),
        ),
    ]
