# Generated by Django 5.2.5 on 2025-09-06 20:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0010_customuser_is_name_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='first_name', unique=True),
        ),
    ]
