# Generated by Django 5.2.6 on 2025-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0014_customuser_iletisim_bilgilerimi_goster'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
