# Generated by Django 5.2.6 on 2025-09-09 23:45

import autoslug.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0016_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=datetime.datetime(2025, 9, 9, 23, 45, 10, 262637, tzinfo=datetime.timezone.utc), editable=False, populate_from='ilan_baslik', unique=True),
            preserve_default=False,
        ),
    ]
