# Generated by Django 5.2.6 on 2025-09-09 23:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0018_alter_ilan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='ilan_baslik', unique=True),
        ),
    ]
