# Generated by Django 5.2.6 on 2025-09-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0019_alter_ilan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
