# Generated by Django 5.2.6 on 2025-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0020_ilan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='goruntulenme_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
