# Generated by Django 5.2.6 on 2025-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0021_ilan_goruntulenme_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goruntulenme_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
