# Generated by Django 5.2.6 on 2025-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0022_customuser_goruntulenme_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KYC Servis ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(default='pending', max_length=50, verbose_name='KYC Durumu'),
        ),
    ]
