# Generated by Django 5.2.6 on 2025-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0023_customuser_kyc_id_customuser_kyc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='kyc_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='kyc_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tckno',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
