# Generated by Django 5.2.6 on 2025-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0024_remove_customuser_kyc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
