# Generated by Django 5.2.6 on 2025-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0025_customuser_dogum_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
