# Generated by Django 5.2.6 on 2025-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0026_customuser_tc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
