# Generated by Django 5.2.6 on 2025-09-16 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0027_customuser_instagram_customuser_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('icerik', models.ImageField(upload_to='portfolios/')),
                ('aciklama', models.TextField()),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolyo',
                'verbose_name_plural': 'Portfolyolar',
                'db_table': 'portfolyo',
            },
        ),
    ]
