# Generated by Django 5.2.6 on 2025-12-03 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enufak_app', '0028_portfolyo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('puan', models.IntegerField()),
                ('yazan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yazan', to=settings.AUTH_USER_MODEL)),
                ('yazilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yazilan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Yorumu',
                'verbose_name_plural': 'Kullanıcı Yorumları',
                'db_table': 'kullanici_yorumu',
            },
        ),
    ]
